dist: trusty
sudo: false
language: node_js
node_js: node
cache: yarn

deploy:
  provider: npm
  email:
    secure: dOKrqiUWGs+w83NdUqeyhULjqJ8ByVqCyM7vV8vBcaIAPH+2Fmr9soj+nAz+F2yRf2RZJgI0/EYwRdKSKJYX03IVUHqVpId9tmaNrHkO4ikhoSefow+u1rbpyKFxNPxBcbfLh+tiynzdNRaVkLomM8HWVY1e/wjGgi3Ogtd0OYDtLLUmgTuPCsmfB1I7rFvNur1oFW3Ymvek6c2AsU6kTZbVHnGHIKR/W5VdH63+UC1dZqAh0c5EduCTeNd9hOz/RT7fIy2wn3GuAKrTcsezAbUFH1EaDeVC8Hl/dJeZouCXgwe+VgiZdjL4AfuSplt8lkCZnlvmTjy7+7GOF89cy2xjuE5sTf+JF/wYtjvd4PhatBY1p9MVPSq8xNmvQ2UqA9fV6G18YRgvF6cy89K97QnZTVGbUqEolZv8exO2Wr6I4/jB8xzTGoot3UnfmHA2Q8LiDMOm/pY+gYgUOVX0q4SA/R1amZJOkeuFfQT63G6LamJ16HTZeABe/kcwvz+DXHpfSqhDnWUYiPIQxN2OohY06uTJ+xsWjnRtWjSO2tjSCeWAa0ypuJ4BHMS+ZMo9r6P48N4u/cNm/o0khlbWgvCA72nCq7G5IwWSprMEpXX9aM2XB+7DmDEVcMmNGRuWo/36jS6sGbp38GCxvK+4cE29INcokiDcebZkILSdMAQ=
  api_key:
    secure: uMsqzu5bRBxXp53vKDt81NctVmaIj3QPARw1ybja7gS75EpkVsFgcwGgIC+gkfxsr2iUFbRFBtzNwL9QJxa+TYRTawNP8x0KDODFg5mn8zOJKtYvHvPcB5mFS5HWKjzycW5m+CfPaFO45LegzBUxKlzM86qKcO2OqTLBR+nWEbaH3WaEeWU9oNCGoLXoBfyIUJ200dVbAiarhAeMtPDsOcsNdXnsFmkLJu1I7MLW3IUTlZlxgP45+Ei4H+kkqiLk1zE6EgX6Nk3mhLVMapxb1CqrPV8oAtO0TZUzR6vnKdb0dyxJ83vzvpS90ndL57YjAW8UWqAb+NV9clYhmPqK0a2tYcIiiU9fF7NNOR5K6aW8+jC6ZZAwJJ+ft1uDscGToxFtZXGClQUkuCatT/bNVgxgMPousmjBuyBHXcdDoXnMRKD8HYTAwah8cJjLWRRjWnECIh5ph7NqsvaA3evf5ARcInEIl6N5crTbHInPuL4eoq1YA+5yka+ZMpzoC2wiMV0V9nggnAK07YZywyoYEjCxGSpuZxWozOB+vYO4fmv+qkTBIbfEv17yH7+ksvyR1M5aEk2BVzqTQt/us3T82ooIpx0Sg+SILwt8K6lbjWqVFPQIQFMw8KMPc+979S/dvaqLCLSrQh58tZ2KuZltMlcGn02IULiNgZulIgTl6hw=
  on:
    tags: true
